### ISSUE TITLE
MVP/MoreVP switching fast RC deposit

### ISSUE THREAD

**Issue by pthomalla** [omisego/plasma-contracts#114] opened 2019-06-04 12:55 UTC
After rc deposit, user can trade on dex without waiting for block.

1. User make rc deposit
2. Operator give a signature to dex, 
2. User can trade without waiting

Dex can use signature from Operator to start mvp chain transaction.
No need to freeze utxo in dex accounts.

**Comment by paulperegud** [comment] 2019-06-08 18:10
Basically this allows trader to have settlement in the same block as deposit.

**Comment by paulperegud** [comment] 2019-06-10 07:55
Necessary conditions:
a) deposit is being done with MoreVP 
b) operator is confirming that correct deposit was emitted by trader with a signature of the operator.

Some more clarification on why it is possible.

Q. Is the deposit safe from operator going rogue? Why?
A. Yes, it is. Because deposit's spend (the settlement) is done using MVP. This spend can't be used to challenge exit from the deposit without confirmation sig on the settlement. Confirmation sig will not be produced if block is withheld / incorrect.

Q. Why the settlement can spend the unconfirmed deposit?
A. Ban on spending of unconfirmed outputs is there because of the safety of those outputs. And that is covered by question above. And the issue of settlement referring the deposit, which `txpos` is not yet confirmed can be solved by using `output_id` instead of `utxo_pos`.

Q. Why operator's signature is needed?
A. If trader refers to non-existent deposit, the venue will produce invalid settlement. Such settlement would get rejected the operator, so venue would loose some time. The venue needs reasons to believe that deposit exists. This is what operator's signature is for - it's a confirmation from operator that trader indeed has signed and emitted the deposit, that the fee is right, and that there is no double-spend. Why the signature is enough? Because the case above is equivalent of operator censoring the venue - operator can do that anyway, he does not need to cheat by signing and than censoring. So signature is there just to prevent trader from cheating.

**Comment by boolafish** [comment] 2019-06-11 02:42
I think this makes it possible for a block to have: [deposit --> settlement]
However, I don't think this enables: [settlement -> deposit --> settlement] in same block.

In other words, this does not replace all the benefit from keeping the money on exchange (?).
In a market of continuous trading, it seems to me we still need to keep money on exchange.

**Comment by kasima** [comment] 2019-06-12 07:04
I believe the possibility for [deposit ➡️settlement] is only for "fast orders," where funds land fully back into the user's wallet, but not necessarily for an additional order. This may be useful for a retail trader.

**Comment by boolafish** [comment] 2019-10-28 01:03
close this as we have understood the idea and no more action item on this.

**Closed by boolafish** 2019-10-28 01:03 UTC
